export type Project = {
  id: string
  title: string
  shortDescription: string
  fullDescription: string
  context: string
  role: string
  architecture: string
  results: string
  nextSteps: string
  tags: string[]
  featured: boolean
  image?: string
  liveUrl?: string
  githubUrl?: string
  demoUrl?: string
}

export const projects: Project[] = [
  {
    id: "highlevel-credentials",
    title: "HighLevel Credentials Platform",
    shortDescription: "Certifier/Canvas-style credentialing tool with design, issuance, verification, and analytics.",
    fullDescription: "Build a Certifier/Canvas-style credentialing tool with design, issuance, verification, and analytics.",
    context: "Multi-tenant branding, bulk issuance, and secure verification across internal apps.",
    role: "Led frontend architecture; designed visual editor, CSV bulk flows, and issuer/recipient portal.",
    architecture: "React/TypeScript, Canvas APIs, Module Federation, API integrations, UUID verification, analytics dashboards.",
    results: "Launch of editor and issuance workflows; verification and sharing to social networks. [ADD METRIC]",
    nextSteps: "Add revocation lists, webhooks, and extended analytics.",
    tags: ["React", "TypeScript", "Canvas APIs", "Module Federation", "Analytics", "WYSIWYG"],
    featured: true,
    image: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&h=600&fit=crop",
    liveUrl: "[ADD LINK]",
    githubUrl: "[ADD LINK]",
  },
  {
    id: "highlevel-courses",
    title: "HighLevel Courses Platform",
    shortDescription: "Creator-led course + community builder with multimedia, quizzes, drip, payments, and CRM analytics.",
    fullDescription: "Creator-led all-in-one course and community builder. Needed fast authoring, responsive previews, and growth features.",
    context: "Real-time editing, device previews, mobile parity, and accessibility requirements.",
    role: "Built Course Builder/Preview, i18n subtitles, threaded comments, themes; shipped mobile via Capacitor.",
    architecture: "React/Next.js/TypeScript, SSR where needed, Module Federation, Firebase integrations, responsive emulation.",
    results: "Faster authoring and improved engagement. Higher completion rates. [ADD METRIC]",
    nextSteps: "Adaptive learning paths and richer assessment analytics.",
    tags: ["React", "Next.js", "TypeScript", "Module Federation", "Capacitor", "Firebase", "SSR"],
    featured: true,
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=600&fit=crop",
    liveUrl: "[ADD LINK]",
  },
  {
    id: "dmrv-platform",
    title: "DMRV Web App (Carbon Verification)",
    shortDescription: "Digital Measurement, Reporting & Verification for environmental data with real-time updates.",
    fullDescription: "Digital Measurement, Reporting & Verification for environmental data; secure, real-time reporting.",
    context: "Large datasets, auth & permissions, interoperability with external systems.",
    role: "Owned architecture to deployment; engineered a reusable component library and live API integration.",
    architecture: "React, Next.js, TypeScript, shadcn/ui, SSR, caching, structured state management.",
    results: "High-performance data views and reliable reporting. Reduced verification time. [ADD METRIC]",
    nextSteps: "Role-based dashboards and audit trails.",
    tags: ["React", "Next.js", "TypeScript", "Shadcn UI", "SSR", "Real-time"],
    featured: true,
    image: "https://images.unsplash.com/photo-1569336415962-a4bd9f69cd83?w=800&h=600&fit=crop",
    demoUrl: "[ADD LINK]",
  },
  {
    id: "carbon-shop",
    title: "Carbon Shop (Trading Platform)",
    shortDescription: "One-stop platform to trade carbon credits with real-time updates and RBAC.",
    fullDescription: "Carbon credit trading marketplace with role-based access control and real-time market updates.",
    context: "RBAC, live pricing, visibility for stakeholders in carbon markets.",
    role: "Led frontend architecture; dashboards for trades and audit logs; mentored juniors.",
    architecture: "Angular (component-driven), Firebase realtime sync, secure RBAC, Redux-like state management.",
    results: "Instant feedback on trades and better operational visibility. [ADD METRIC]",
    nextSteps: "Advanced order types and anomaly detection.",
    tags: ["Angular", "Firebase", "Real-time", "RBAC", "Trading"],
    featured: false,
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=600&fit=crop",
    liveUrl: "[ADD LINK]",
    githubUrl: "[ADD LINK]",
  },
  {
    id: "afis-schoolbus",
    title: "AFIS Schoolbus Tracking",
    shortDescription: "Cross-platform mobile app with GPS tracking, notifications, and multi-tenant accounts.",
    fullDescription: "School transportation management system with real-time GPS tracking and parental notifications.",
    context: "Safety-critical application requiring reliable GPS tracking and instant notifications for parents and schools.",
    role: "Cross-platform mobile development with real-time location tracking and notification system.",
    architecture: "React Native, Firebase, Google Maps API, Push Notifications, multi-tenant architecture.",
    results: "Improved student safety and parental peace of mind with real-time tracking. [ADD METRIC]",
    nextSteps: "Route optimization and predictive arrival times.",
    tags: ["React Native", "Firebase", "GPS", "Mobile", "Real-time"],
    featured: false,
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=600&fit=crop",
    liveUrl: "[ADD LINK]",
    githubUrl: "[ADD LINK]",
  },
  {
    id: "khajuraho-expo",
    title: "Khajuraho Expo",
    shortDescription: "Multilingual audio guides, QR code navigation, and 360° media map for cultural tourism.",
    fullDescription: "Interactive tourism application with immersive audio guides and location-based navigation for temples.",
    context: "Tourism application requiring offline capabilities, multi-language support, and interactive maps.",
    role: "Frontend development with focus on PWA capabilities, audio integration, and interactive 360° maps.",
    architecture: "React, PWA, Web Audio API, Geolocation API, Service Workers, 360° image rendering.",
    results: "Engaging tourist experience with offline support and multiple language options. Enhanced visitor engagement.",
    nextSteps: "AR features and enhanced 360° virtual tours.",
    tags: ["React", "PWA", "Audio", "Maps", "Tourism", "i18n"],
    featured: false,
    image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&h=600&fit=crop",
    liveUrl: "[ADD LINK]",
  },
  {
    id: "hyre-me",
    title: "Hyre Me (Local Jobs)",
    shortDescription: "React Native app with WebSocket notifications, dashboards, and optimized data flows.",
    fullDescription: "Local job marketplace connecting employers with job seekers in their area with real-time features.",
    context: "Job platform requiring real-time communication, location-based matching, and instant notifications.",
    role: "Full-stack development with emphasis on real-time features and mobile-first design.",
    architecture: "React Native, WebSocket, Node.js, MongoDB, Geolocation API, push notifications.",
    results: "Active local job marketplace with real-time job alerts and high engagement rates.",
    nextSteps: "AI-powered job matching and enhanced recommendation engine.",
    tags: ["React Native", "WebSocket", "MongoDB", "Real-time", "Mobile"],
    featured: false,
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop",
    liveUrl: "[ADD LINK]",
  },
  {
    id: "innovative-service-center",
    title: "Innovative Service Center",
    shortDescription: "End-to-end SaaS for bookings, workflows, invoicing, and analytics.",
    fullDescription: "Complete service center management system with booking, invoicing, and customer management.",
    context: "Service business requiring comprehensive management and automation of operations.",
    role: "Full-stack SaaS development from concept to deployment with focus on workflow automation.",
    architecture: "MERN Stack, Node.js, Express, MongoDB, React, automated workflows, payment integration.",
    results: "Streamlined service operations and improved customer satisfaction. Reduced manual work by 60%.",
    nextSteps: "Mobile app and advanced analytics with business intelligence.",
    tags: ["MERN", "SaaS", "Node.js", "MongoDB", "Automation"],
    featured: false,
    image: "https://images.unsplash.com/photo-1556742111-a301076d9d18?w=800&h=600&fit=crop",
    demoUrl: "[ADD LINK]",
  },
  {
    id: "interactive-portfolio",
    title: "Interactive Portfolio (Haspr)",
    shortDescription: "GSAP/Three.js/WebGL; performance-tuned animations and accessibility.",
    fullDescription: "Creative portfolio website with advanced animations and 3D elements showcasing technical skills.",
    context: "Portfolio site requiring unique visual experience while maintaining excellent performance.",
    role: "Frontend development with focus on advanced animations, 3D graphics, and performance optimization.",
    architecture: "React, GSAP, Three.js, WebGL, performance profiling, lazy loading.",
    results: "Engaging visual experience with smooth 60fps animations and excellent Lighthouse scores.",
    nextSteps: "Enhanced 3D interactions and WebGL shader effects.",
    tags: ["React", "GSAP", "Three.js", "WebGL", "Animations"],
    featured: false,
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop",
    liveUrl: "[ADD LINK]",
    githubUrl: "[ADD LINK]",
  },
]
